### ISSUE TITLE
step0 POST error

### ISSUE THREAD

**Issue by karpet** [BlueprintKansas/ksvotes.org#386]
```
Stack trace
builtins:AttributeError: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
File "/app/.heroku/python/bin/gunicorn", line 11, in <module>
File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 223, in run
File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 203, in run
File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 616, in spawn_workers
File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 124, in run
File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 68, in run_for_one
File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 30, in accept
File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/api/web_transaction.py", line 1286, in _nr_wsgi_application_wrapper_
File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/api/web_transaction.py", line 813, in __init__
File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/api/web_transaction.py", line 1175, in _nr_wsgi_application_wrapper_
File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/hooks/framework_flask.py", line 45, in _nr_wrapper_handler_
File "/app/app/decorators/insession.py", line 56, in decorated
File "/app/app/main/starter_views.py", line 37, in index
File "/app/.heroku/python/lib/python3.6/site-packages/wtforms/form.py", line 212, in __call__
File "/app/.heroku/python/lib/python3.6/site-packages/flask_wtf/form.py", line 88, in __init__
File "/app/.heroku/python/lib/python3.6/site-packages/wtforms/form.py", line 278, in __init__
File "/app/.heroku/python/lib/python3.6/site-packages/wtforms/form.py", line 132, in process
File "/app/.heroku/python/lib/python3.6/site-packages/wtforms/fields/core.py", line 287, in process
File "/app/app/main/forms/step_0.py", line 14, in process_formdata
```

**Comment by karpet** [comment]
seems to be a bad DOB value regex match.
